<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class LatamDynamicToolText extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::table('dynamic_tools_texts')->where(['country_id' => '1','locale_id' => '4','key' => 'gasoline_demand'])->update(['content' => 'La demanda de gasolinas en Argentina fue de 2,566 millones de galones en 2024 (9,712 millones de litros). Se cuenta con la siguiente participación por tipo de gasolina: 76% como Nafta Súper / Grado 2 (RON 93 min) y 24% restante como Nafta Ultra / Grado 3 (RON 97 min). Comúnmente se suministran combustibles de mayor octanaje al mercado. Argentina produce casi la totalidad de la gasolina, las importaciones en 2024 fueron 75 millones de litros por año.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '2','locale_id' => '4','key' => 'gasoline_demand'])->update(['content' => 'El consumo de gasolina en 2024 fue de 2,348 millones de litros (620 millones de galones). La gasolina especial (regular) representa  96% de la demanda del país y la gasolina premium solo el 4%. La mayor parte de la gasolina contiene etanol. En 2024, se importó el 51.4% de la gasolina, principalmente de Brasil, Chile, Estados Unidos y Argentina. La producción ha decrecido anualmente en los últimos cuatro años.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '3','locale_id' => '4','key' => 'gasoline_demand'])->update(['content' => 'El consumo de gasolinas en Chile en 2024 se mantiene por encima de los 1,300 millones de galones por año (5,000 millones de litros), repartidos entre los tres grados que se comercializan: RON 93 (AKI 87), RON 95 (AKI 88) y RON 97 (AKI 92). El grado RON 93 representa el 28% del mercado de gasolinas. Chile cuenta con una especificación especial para la Región Metropolitana de Santiago, que es más estricta que la del resto del país. La empresa del estado, ENAP, produce alrededor del 80% del consumo en Chile (CNE). En 2023 y 2024 la producción se normalizó tras las reducciones ocasionadas en 2022 por mantenimiento y restricciones ambientales en refinerías. Las importaciones de gasolina y componentes provienen principalmente de Estados Unidos. Aunque en las refinerías solo se producen RON 93 y RON 97, en estaciones de servicio se mezclan por partes iguales ambas gasolinas para producir RON 95.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '4','locale_id' => '4','key' => 'gasoline_demand'])->update(['content' => 'En 2024, la demanda de gasolinas en Colombia fue cercana a 2,023 millones de galones (7,658 millones de litros). Actualmente la gasolina Extra E10 (RON 97 – AKI 94) solo participa un 3% en volumen, mientras que el 97% restante domina la gasolina Corriente E10 (RON  89 – AKI 84). Colombia tiene una producción que cubrió el 65% del consumo nacional, por lo que recubre a importaciones con países extranjeros, entre ellos Estados Unidos.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '5','locale_id' => '4','key' => 'gasoline_demand'])->update(['content' => 'En 2024, el consumo de gasolina fue de 378 millones de galones (1429 millones de litros). Cuenta con dos gasolinas RON 95 y RON 91, con una participación de mercado de 45% RON 91 y 55% RON 95. La refinería de Limón dejó de operar en 2012, así que el suministro es de importaciones provenientes de Estados Unidos y Europa en menor grado.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '6','locale_id' => '4','key' => 'gasoline_demand'])->update(['content' => 'El mercado nacional de gasolinas en Ecuador alcanzó los 1,188 millones de galones (4,498 millones de litros) para 2024. Actualmente, se decretó un nuevo plan de implementación de nuevas gasolinas, donde existen oficialmente 4 grados de gasolina en 5 diferentes tipos conforme a la normatividad de combustibles (NTE INEN 935:2021): Extra (RON 85), Ecopaís E10 (RON 85), Ecoplus (RON 89), Súper (RON 92), Súper Premium (RON 95). La Super Premium (RON 95) sustituiría paulatinamente a la Súper (RON 92); La gasolina Ecoplus (RON 89) se introdujo recientemente al mercado. Ecuador cuenta con producción propia e importa naftas (gasolinas no terminadas) para cubrir su demanda interna.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '7','locale_id' => '4','key' => 'gasoline_demand'])->update(['content' => 'En 2024, la demanda de gasolina fue 328 millones de galones (1,243 millones de litros). La gasolina regular RON 91 representó el 51% del volumen consumido mientras que la gasolina superior RON 95 alcanzó un 49%. La participación de gasolina superior se ha mantenido en estos niveles desde hace diez años. La gasolina se importa en su totalidad y  se distribuye principalmente por las compañías Chevron, Puma y Uno; teniendo como origen importaciones desde Estados Unidos.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '8','locale_id' => '4','key' => 'gasoline_demand'])->update(['content' => 'La demanda de gasolina fue de 778 millones de galones en 2024 (2,946 millones de litros).Se cuentan con dos especificaciones de gasolina: Regular (RON 91 - AKI 85) y Superior (RON 95 - AKI 89). El 55% del consumo es gasolina Regular. Guatemala no cuenta con una producción nacional de gasolinas, por lo que recurre totalmente a importaciones principalmente desde Estados Unidos.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '9','locale_id' => '4','key' => 'gasoline_demand'])->update(['content' => 'En 2024, la demanda de gasolina fue de 374 millones de galones (1,290 milliones litros). La gasolina Regular RON 91 representó el 46% mientras que la gasolina Superior RON 95 el 54% del consumo nacional. No cuenta con producción de gasolinas, el suministro es con producto importado principalmente de Estados Unidos.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '10','locale_id' => '4','key' => 'gasoline_demand'])->update(['content' => 'En 2024, el consumo de gasolina fue de 230 millones de galones (869 millones de litros).La participación de la gasolina regular (AKI 87) fue de 34% en volumen de la gasolina premium (AKI 90) de 66%. La producción de gasolina fue 34 millones de galones (130 millones de litros) y se importaron 195 millones de galones (739 millones de litros) principalmente de Estados Unidos. ']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '11','locale_id' => '4','key' => 'gasoline_demand'])->update(['content' => 'La demanda de gasolina en México es de 12,200 millones de galones por año (46,000 millones de litros). Actualmente existen dos grados de octanaje: Regular (AKI 87) y Premium (AKI 91). La gasolina regular es la de mayor consumo con una participación del 90%. Adicionalmente existen especificaciones mas estrictas para las Zonas Metropolitanas (Ciudad de México y para Guadalajara y Monterrey). México produce cerca del 40% del consumo del país e importa el resto principalmente desde Estados Unidos.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '12','locale_id' => '4','key' => 'gasoline_demand'])->update(['content' => 'En 2024 la demanda fue de 149 millones de galones (565 millones de litros).La refinería de Nicaragua es la única en Centroamérica que produce actualmente gasolina, cubriendo el 33% de la demanda. El faltante se importaba anteriormente desde Venezuela quien desde 2016 fue desplazado por Estados Unidos. Existen dos gasolinas en el país, regular con un 29% de participación en volumen en el mercado y premium con un 71%.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '13','locale_id' => '4','key' => 'gasoline_demand'])->update(['content' => 'En 2024 el consumo fue de 358 millones de galones (1356 millones de litros). La gasolina regular (RON 91) representó  el 36%  del  volumen consumido mientras que la premium (RON 95) alcanzaba un 64%. Se importa la totalidad de la gasolina provenientes de Estados Unidos, Holanda y Alemania.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '14','locale_id' => '4','key' => 'gasoline_demand'])->update(['content' => 'En 2024, Perú superó los 900 millones de galones de gasolina (3,000 millones de litros). A partir de 2023 se implementó un programa para aumentar el octanaje; las gasolinas RON 84 y RON 90 se comercializarán como Gasolina Regular (RON 90) con el 70% de participación del mercado, y las gasolinas RON 95, RON 97 y RON 98 pasarán a ser Gasolina Premium (RON 95) con el 30% restante. Para gasolinas con etanol (gasoholes) el octano aumenta un número de octano (RON 91 y RON 96 respectivamente). La mayoría de sus gasolinas son producidas nacionalmente por Petroperú, Repsol y Primax. Se importa entre el 10 y 15% de su demanda interna a países vecinos, Estados Unidos y Europa.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '15','locale_id' => '4','key' => 'gasoline_demand'])->update(['content' => 'La demanda de gasolinas se cubre con la producción local que representa un 15% e importaciones provenientes de Estados Unidos, Trinidad y Tobago, Caribe, entre otros. En 2024, el consumo de gasolina fue 562 millones de galones (2,126 millones de litros). El consumo de regular fue de 35% en volumen del total nacional y el de premium de 65%. El gobierno dominicano aplica subsidios a las gasolinas']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '16','locale_id' => '4','key' => 'gasoline_demand'])->update(['content' => 'En 2024, el consumo de gasolina fue de 245 millones de galones (926 millones de litros). La Gasolina Super con un RON 95 representó el 84% del total de la demanda en volumen, el resto fue Gasolina Premium con un RON 97. La producción de gasolinas en Uruguay alcanzó los 125 millones de galones (471 millones de litros) y cubre 64% de la demanda con importaciones.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '1','locale_id' => '4','key' => 'ethanol_text'])->update(['content' => 'La política sobre etanol es de ser autosuficientes en la producción y suministro de etanol para gasolinas. El requerimiento es variable en función de la producción nacional, actualmente es de 12% de etanol en gasolina (Ley 27.640). Se encuentra en discusión el aumento del contenido de etanol a 15%. La producción iguala al consumo, habiendo pequeñas exportaciones e importaciones a otros países.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '2','locale_id' => '4','key' => 'ethanol_text'])->update(['content' => 'Conforme a la Decreto Supremo No. 4718 emitida por Ministerio de Hidrocarburos y Energías / ANH , se permiten gasolinas  E8 y E12. El suministro de etanol es con etanol que se produce localmente. Existen cinco empresas: Azúcar Aguaí, Unagro, Poplar Capital, Granosol,  y Guabirá.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '3','locale_id' => '4','key' => 'ethanol_text'])->update(['content' => 'Conforme al Decreto Supremo 56 emitido por el Ministerio de Energía se permite el uso de hasta 5% de etanol, pero no se utiliza actualmente por barrera regulatoria. Chile no produce ni importa etanol. Se analiza actualmente el uso de etanol como una medida para apoyar los planes de descarbonización de la economía.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '4','locale_id' => '4','key' => 'ethanol_text'])->update(['content' => 'Conforme a la Resolución 40103 de 2023, es obligatorio la mezcla de gasolina con etanol en Colombia, en los centros urbanos de más de 500.000 habitantes. Actualmente, se ha establecido un 10% de mezcla, permitiendo una mezcla de etanol con gasolina en Colombia menor en casos excepcionales. El E10 es el grado predominante en el país excepto en frontera con Venezuela. El suministro de etanol proviene de importaciones de Estados Unidos y de producción local.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '5','locale_id' => '4','key' => 'ethanol_text'])->update(['content' => 'Conforme a la nómina de combustibles de Costa Rica (INTE E1:2019) se permite la mezcla de gasolina con hasta 10% de etanol. Sin embargo, solo se mezcla menos del 0.2% en volumen, debido a que no hay un consenso entre los distintos actores para su implementación. La producción en 2024 fue de 8.9  millones de galones (33 millones de litros y se exportaron 7.2 millones de galones (27 millones litros principalmente a Europa. El consumo local representa menos del 0.2% en volumen de gasolina. Se encuentra en proceso de implementación las mezclas de E10, la expectativa del Gobierno es que sea en 2026.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '6','locale_id' => '4','key' => 'ethanol_text'])->update(['content' => 'Hoy en día, la norma de calidad no especifica cuanto etanol debe mezclarse. Se comenzó a mezclar etanol desde 2009. Actualmente se consumen mezclas de E10 en gasolina Ecoplus y Super. La gasolina Ecopais solo se suministra en algunas provincias y su promedio de etanol oscila en 3-4% La producción nacional de etanol satisface el consumo interno y se usa en otras industrias y/o se exporta a países vecinos.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '7','locale_id' => '4','key' => 'ethanol_text'])->update(['content' => 'En El Salvador no hay un mandato de etanol. Tiene potencial para producir etanol con base a maíz y azúcar. En los últimos años ha habido interés en su uso.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '8','locale_id' => '4','key' => 'ethanol_text'])->update(['content' => 'Se permite hasta 10% de etanol en gasolina (Acuerdo Gubernativo 159-2023, MEM). Cuenta con producción de etanol avanzado que se exporta a Europa, pero no se mezcla en el país por falta de consenso entre los diferentes actores locales. Guatemala es el principal productor de etanol en Centroamérica. Se encuentra en proceso de análisis la implementación de E10 para 2026.-2027.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '9','locale_id' => '4','key' => 'ethanol_text'])->update(['content' => 'En Honduras no hay un mandato de etanol. Pero se encuentra en discusión un proyecto de ley para el uso de biocombustibles.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '10','locale_id' => '4','key' => 'ethanol_text'])->update(['content' => 'Conforme a la norma de combustibles (JS 341:2017), se obliga la mezcla de 10% v/v de etanol en gasolina. Anteriormente, se producía el etanol localmente para Petrojam, sin embargo, actualmente se importa casi todo el etanol de Estados Unidos.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '11','locale_id' => '4','key' => 'ethanol_text'])->update(['content' => 'Conforme a la NOM-016-CRE de 2016, se permite el uso de etanol hasta 5.8% en todo el país, excepto en las Zonas Metropolitanas. El consumo actual de etanol equivale al 1.06% del consumo de gasolina Resto del País a nivel nacional. Se publicó una nueva ley de Biocombustibles en 2025 que promueve el uso de residuos agrícolas para su producción. Adicionalmente,  existen esfuerzos estatales para alcanzar mayores volúmenes de consumo de etanol (p.e. Tamaulipas). ']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '12','locale_id' => '4','key' => 'ethanol_text'])->update(['content' => 'De acuerdo con el Ministerio de Energía y RTCA, en Nicaragua no existe mandato de etanol.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '13','locale_id' => '4','key' => 'ethanol_text'])->update(['content' => 'En 2011 se autorizó la mezcla con 2% v/v y un aumento gradual hasta alcanzar 10% v/v en 2016. Sin embargo, en 2013 se limitó a 5% v/v y en 2014 se dejó de utilizar por disputas políticas. Se espera la implementación de mandato de una mezcla obligatoria de hasta el 10% en 2026-2027.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '14','locale_id' => '4','key' => 'ethanol_text'])->update(['content' => 'Se permiten gasolinas con etanol con 7.8% v/v (Decreto Supremo N.° 021-2007-EM: MINEM). Perú produce etanol de caña de azúcar principalmente para exportación a Europa. Adicionalmente se importa etanol  principalmente de Estados Unidos para mezclado local.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '15','locale_id' => '4','key' => 'ethanol_text'])->update(['content' => 'República Dominicana no cuenta actualmente con mandato de etanol.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '16','locale_id' => '4','key' => 'ethanol_text'])->update(['content' => 'Se permiten mezclas de hasta 10% v/v. En Uruguay existen dos plantas de etanol, con una capacidad en conjunto de 100 millones de litros. La materia prima utilizada es caña de azúcar, sorgo y maíz. En 2024, el consumo de etanol fue de 24 millones de galones (91 millones de litros). La producción suministra la demanda. Se realizan importaciones por balance.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '1','locale_id' => '2','key' => 'gasoline_demand'])->update(['content' => 'Argentina’s total gasoline demand was 2,566 million gallons per year  in 2024 (9,712 million liters per year), with a market share of approximately 76% as Nafta Súper / Grado 2 (RON 93 min  – AKI 87) and 24% as Nafta Ultra / Grado 3 (RON 97 min – AKI 92). Octane delivered to market is usually higher than the minimum required. The demand for gasoline is supplied by local production, requiring imports of less than 75 million liters per year.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '2','locale_id' => '2','key' => 'gasoline_demand'])->update(['content' => 'In 2024, gasoline demand was 620 million gallons (2,348 million liters). Gasoline Imports represented 51.4% of demand, and are supplied from Brazil, Chile, Argentina, and the United States. Regular Gasoline (Especial) with 85 RON Octane represented 96% of demand and Premium Gasoline with a 95 RON octane the rest. Gasoline production has decreased in the last years.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '3','locale_id' => '2','key' => 'gasoline_demand'])->update(['content' => 'Chile\'s gasoline consumption is currently over 1,300 million gallons per year (5,000 million liters) in three grades: RON 93 (AKI 87), RON 95 (AKI 88) and RON 97 (AKI 92). There is a more stringent quality specification for Santiago Metropolitan Area. In 2024, the market share of RON 93 gasoline was 28%. Government company ENAP produces 80% of the total demand (CNE). Gasoline imports made in the country come mainly from the United States. Refineries only produce RON 93 and RON 97, gasoline RON 95 is blended from these grades in gas stations.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '4','locale_id' => '2','key' => 'gasoline_demand'])->update(['content' => 'In 2024,  gasoline consumption in Colombia was 2,023 million gallons (7,658 million liters). Market share was 3% for Extra gasoline E10 (RON 97 – AKI 94) and 97% for Regular gasoline (regular) E10 (RON 89 – AKI 84). Local production supplies 65% of total demand. United States is the main source of gasoline imports.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '5','locale_id' => '2','key' => 'gasoline_demand'])->update(['content' => 'In 2024, gasoline demand was 378 million gallons (1429 million liters). Costa Rica has two gasoline RON 95 and RON 91, with a market share of 45% for RON 91 and 55% for RON 95. The Limon refinery stopped production in 2012. Gasoline supply is done with imports mainly from the United States and some from Europe. ']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '6','locale_id' => '2','key' => 'gasoline_demand'])->update(['content' => 'In 2024, gasoline consumption in Ecuador was 1,188 million gallons (4,498 million liters). A new plan was stablished to implement new grades of gasoline: four grades with 5 different types according to the current quality norm (NTE INEN 935:2021): Extra (RON 85), Ecopais E10 (RON 85), Ecoplus (RON 89), Súper (RON 92) and Super Premium (RON 95). Super Premium (RON 95) will gradually substitute Super (RON 92). Gasoline Ecoplus (RON 89) was recently introduced in the market. Ecuador has local production and imports naphtha (unfinished gasolines) to supply national demand.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '7','locale_id' => '2','key' => 'gasoline_demand'])->update(['content' => 'In 2024, gasoline demand was 328 million gallons (1,243 million liters). Regular gasoline RON 91 represented 51% of the volume consumed while Superior gasoline RON 95 reached 49%. Gasoline is supplied only by imports, distributed mainly by Chevron, Puma and Uno companies and imported mainly from the United States.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '8','locale_id' => '2','key' => 'gasoline_demand'])->update(['content' => 'In 2024, gasoline consumption was 778 million galons (2,946 million liters). Gasoline is supplied only by imports, mainly from United States. There are two grades of gasoline: (RON 91 - AKI 85) and Superior (RON 95 - AKI 89). 55% of gasoline is gasoline Regular.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '9','locale_id' => '2','key' => 'gasoline_demand'])->update(['content' => 'n 2024, gasoline demand was 374 million gallons (1,290 million liters). Regular gasoline RON 91 represented 46% while Superior gasoline RON 95 reached 54% of national demand. Honduras does not have gasoline production capacity and supplies its market with imports mainly from the United States.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '10','locale_id' => '2','key' => 'gasoline_demand'])->update(['content' => 'In 2024, gasoline demand was 230 million gallons (869 million liters). Gasoline production was 34 million gallons (130 million liters) and imports 195 million gallons (739 million liters) mainly from United States. Regular grade (AKI 87) had a market share of 34% and Premium grade (AKI 90) 66%.  ']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '11','locale_id' => '2','key' => 'gasoline_demand'])->update(['content' => 'In 2024, gasoline consumption was 12,200 million gallons (46,000 million liters). There are two grades of gasoline, Regular (AKI 87) and Premium (AKI 91). Regular gasoline is the main grade in the market, representing 90% of the volume. There are stringent gasoline specifications for major metropolitan areas in Mexico City, Guadalajara and Monterrey. Demand is much higher than production, making necessary to import 40% of gasoline mainly from the United States.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '12','locale_id' => '2','key' => 'gasoline_demand'])->update(['content' => 'In 2024, gasoline demand was 149 million gallons (565 million liters). Nicaragua is the only country in Central America that has active refinery capacity, which produced 33% of gasoline national demand. The rest of demand is imported, previously from Venezuela and since 2016 mainly from United States. There are two gasoline grades in the country, regular with 29% and premium with 71% of market share.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '13','locale_id' => '2','key' => 'gasoline_demand'])->update(['content' => 'En 2024 demand was 358 million gallons (1356 million liters). Regular gasoline (RON 91) represented 36% of total demand and Superior gasoline (RON 95) 64%. Gasoline is supplied only with imports, mainly from United States, the Netherlands and Germany.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '14','locale_id' => '2','key' => 'gasoline_demand'])->update(['content' => 'In 2024, Peru gasoline consumption surpassed 900 million gallons (3,000 millions liters). Starting in 2023 a program to increase octane in gasoline was implemented; RON84 and RON 90 gasoline are commercialized  as Regular gasoline (RON 91)  with a 70% market participation. RON 95, RON 97 and RON 98 gasolines are now marketed as Premium gasoline (RON 96) with a 30% market share. Gasoline with ethanol (gasohol) is required to meet one additional octane number (RON 91 and RON 96 respectively). Local gasoline supply is done with production from Petroperú, Repsol and Primax. Gasoline imports account for 10 to 15% of demand, and are supplied by local markets, United states  and Europe.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '15','locale_id' => '2','key' => 'gasoline_demand'])->update(['content' => 'National demand is covered up by local production representing 15%, and imports from United States, Trinidad and Tobago, Caribbean, among other countries. In 2024, gasoline consumption was 562 million gallons (2,126 million liters). Regular gasoline consumption was 35% of total demand and premium 65%. The Dominican Government applies subsidies to gasoline prices.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '16','locale_id' => '2','key' => 'gasoline_demand'])->update(['content' => 'In 2024, gasoline demand was 245 million gallons (926 million liters). Super Gasoline with RON 95 represented 84% of total demand and Premium Gasoline with RON 97 the rest. Gasoline production was 125 million gallons (471 million liters) and covers 64% of local demand.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '1','locale_id' => '2','key' => 'ethanol_text'])->update(['content' => 'Argentina\'s policy is self-sufficiency and production and supply of ethanol for gasoline blend. Ethanol concentration varies according to local production.  Currently, the concentration limit is 12% v/v. (Law 27.640) and a future E15 requirement is under discussion. Ethanol production is equal to consumption with some exports and imports from other countries.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '2','locale_id' => '2','key' => 'ethanol_text'])->update(['content' => 'Gasoline E8 and E12 are currently marketed (Decreto Supremo No. 4718:ANH). About 80% of gasoline demand contains ethanol. All ethanol consumed in Bolivia is produced by five local companies: Azúcar Aguaí, Unagro, Poplar Capital, Granosol, and Guabirá.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '3','locale_id' => '2','key' => 'ethanol_text'])->update(['content' => 'Ethanol can be blended up to 5% v/v (Decreto Supremo 56) but it is not used because of regulatory barriers. Chile does not produce or imports ethanol. The use of ethanol is being analyzed to achieve short term goals in the national economy decarbonization program.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '4','locale_id' => '2','key' => 'ethanol_text'])->update(['content' => 'Ethanol blends are obligatory in cities with more than 500,000 habitants. Resolution 40444 of 2023 authorizes the blending of up to 10% ethanol in the country and allows for lower percentages in particular cases. E10 is the predominant grade in the country except on the border with Venezuela. The ethanol supply comes from imports from the United States and from local production.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '5','locale_id' => '2','key' => 'ethanol_text'])->update(['content' => 'Gasoline blends with up to 10% v/v of ethanol are allowed (INTE E1:2019). However, this mandate is not yet reflected on the gasoline market. Current ethanol consumption is less than 0.2% because there is no stakeholder’s consensus for implementation. In 2024, ethanol production was 8.9 million gallons (33 million liters) and ethanol exports mainly to Europe was 7.2 million gallons (27 million liters). Introduction of E10 is expected by the Government in 2026.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '6','locale_id' => '2','key' => 'ethanol_text'])->update(['content' => 'There is no specific mandate for ethanol blending, however there is a permit to blend it with gasoline. Ethanol has been blending in gasoline since 2009. Today the usual blend is E10 for Ecoplus and Super. Ecopais gasoline is supplied in some provinces with an ethanol content  between 3-4%. Gasoline Ethanol is produced ,consumed and exported to neighboring countries for fuel and industrial use.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '7','locale_id' => '2','key' => 'ethanol_text'])->update(['content' => 'El Salvador has no national mandate for ethanol. It has the potential to produce ethanol from maize and sugar cane. In the last year there has been an interest for its use.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '8','locale_id' => '2','key' => 'ethanol_text'])->update(['content' => 'Guatemala allows for blends up to 10% v/v (Acuerdo Gubernativo 159-2023, MEM) but no ethanol is blended in the country because there is no stakeholder’s consensus regarding its implementation. It has local ethanol advanced ethanol production that is exported to Europe. Guatemala is the main ethanol productor in Central America. The  E10 mandate is currently under  analsys for implementation for 2026-2027.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '9','locale_id' => '2','key' => 'ethanol_text'])->update(['content' => 'Honduras has no national mandate for ethanol blends. A new biofuel’s law is under discussion.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '10','locale_id' => '2','key' => 'ethanol_text'])->update(['content' => 'Current gasoline quality norm mandates E10 (JS 341:2017) . Previously, ethanol was supplied with local production to Petrojam, however, in recent years, ethanol is imported from the United States.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '11','locale_id' => '2','key' => 'ethanol_text'])->update(['content' => 'Gasoline quality norm (NOM-016-CRE de 2016) allows blends with a maximum of 5.8% v/v of ethanol  with the exception of metropolitan areas of Valle de Mexico, Guadalajara and Monterrey. Current ethanol use is equivalent to an average of 1.06% in the Rest of the Country grade gasoline. In 2025, a new biofuels law was approved that fosters the production with agricultural and other organic residuals. Recently there are new state level efforts to increase ethanol consumption (e.g. Tamaulipas).']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '12','locale_id' => '2','key' => 'ethanol_text'])->update(['content' => 'According to the Ministry of Energy and RTCA, Nicaragua has no ethanol mandate.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '13','locale_id' => '2','key' => 'ethanol_text'])->update(['content' => 'In 2011, 2% v/v ethanol blends with gasoline were authorized, with a planned gradual increase until reaching 10% v/v by 2016. However, in 2013 it was limited to 5% v/v and by 2014 blending stopped because the only national producer announced its production cease due to political dispute. A new mandate implementation has been approved for E10  and is  expected  to be implemented between 2026 and 2027.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '14','locale_id' => '2','key' => 'ethanol_text'])->update(['content' => 'Blends with 7.8% v/v are allowed (Decreto Supremo N.° 021-2007-EM: MINEM). Peru produces ethanol from sugarcane; however, its destination is mainly the EU market. Ethanol imports from the United States and to a lesser degree from Brazil are used for the national blend.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '15','locale_id' => '2','key' => 'ethanol_text'])->update(['content' => 'Dominican Republic does not currently have an ethanol mandate.']);
        DB::table('dynamic_tools_texts')->where(['country_id' => '16','locale_id' => '2','key' => 'ethanol_text'])->update(['content' => 'Gasoline Blends with up to 10% v/v  are allowed.. In Uruguay there are two ethanol plants with an overall capacity of 100 million liters per year, raw material commonly used are sugar cane, sorghum, and corn. In 2024, ethanol consumption was 24 million gallons (91 million liters).']);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
